# Generated by Django 5.0.7 on 2024-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='plane',
        ),
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='slug',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
