# Generated by Django 5.0.7 on 2024-09-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_fly'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='name',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='fly',
            name='slug',
            field=models.TextField(max_length=99, null=True),
        ),
    ]
