# Generated by Django 5.0.7 on 2024-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_fly_name_fly_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
