# Generated by Django 5.0.7 on 2024-09-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_fly_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='slug',
            field=models.SlugField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='fly',
            name='slug',
            field=models.SlugField(max_length=99, null=True),
        ),
    ]
