# Generated by Django 5.0.7 on 2024-09-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_fly_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
    ]
