# Generated by Django 5.0.7 on 2024-10-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_alter_fly_img_alter_fly_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='img',
        ),
    ]
