# Generated by Django 5.0.7 on 2024-10-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_remove_fly_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='slug',
        ),
        migrations.AddField(
            model_name='fly',
            name='logo',
            field=models.ImageField(null=True, upload_to='airline_logos'),
        ),
    ]
