# Generated by Django 5.0.7 on 2024-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_fly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='slug',
            field=models.SlugField(max_length=99, null=True),
        ),
    ]
