# Generated by Django 5.0.7 on 2024-10-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_remove_fly_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='img',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='fly',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
