# Generated by Django 5.0.7 on 2024-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0015_fly_img_alter_fly_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='img',
        ),
        migrations.AlterField(
            model_name='fly',
            name='travel_date',
            field=models.DateField(null=True),
        ),
    ]
