# Generated by Django 5.0.7 on 2024-10-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0016_remove_fly_img_alter_fly_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='slug',
        ),
    ]
