# Generated by Django 5.0.7 on 2024-10-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0017_remove_fly_name_remove_fly_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='logo',
            field=models.ImageField(null=True, upload_to='airline_logos'),
        ),
    ]
