# Generated by Django 5.0.7 on 2024-10-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0018_fly_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='airline',
        ),
        migrations.AddField(
            model_name='fly',
            name='name',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='fly',
            name='slug',
            field=models.SlugField(max_length=99, null=True),
        ),
    ]
