# Generated by Django 5.0.7 on 2024-10-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0019_remove_fly_airline_fly_name_fly_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='slug',
        ),
        migrations.AddField(
            model_name='fly',
            name='airline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
