# Generated by Django 5.0.7 on 2024-10-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0022_fly_name_fly_slug_alter_fly_airline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='logo',
        ),
    ]
