# Generated by Django 5.0.7 on 2024-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0026_fly_name_fly_slug_alter_fly_airline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='airline',
        ),
        migrations.AddField(
            model_name='fly',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/plane/img'),
        ),
    ]
