# Generated by Django 5.0.7 on 2024-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0027_remove_fly_airline_fly_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/plane/img'),
        ),
    ]
