# Generated by Django 5.0.7 on 2024-10-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0028_alter_fly_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='logo',
            field=models.ImageField(null=True, upload_to='airline_logos'),
        ),
    ]
