# Generated by Django 5.0.7 on 2024-10-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0029_alter_fly_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='logo',
        ),
        migrations.AddField(
            model_name='fly',
            name='image',
            field=models.ImageField(default='', upload_to='air/images'),
        ),
    ]
