# Generated by Django 5.0.7 on 2024-10-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0030_remove_fly_logo_fly_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='image',
        ),
    ]
