# Generated by Django 5.0.7 on 2024-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_flights_delete_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='price',
        ),
        migrations.AddField(
            model_name='flights',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
