# Generated by Django 5.0.7 on 2024-09-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_flights_desc_remove_flights_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='date',
            new_name='arrival_date',
        ),
    ]
