# Generated by Django 5.0.7 on 2024-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_date_flights_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
