# Generated by Django 5.0.7 on 2024-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_flights_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='time',
            new_name='arrivaltime',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='arrival_date',
        ),
        migrations.AddField(
            model_name='flights',
            name='departuretime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
