# Generated by Django 5.0.7 on 2024-09-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_time_flights_arrivaltime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='arrivaltime',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='departuretime',
            new_name='departure_time',
        ),
    ]
