# Generated by Django 5.0.7 on 2024-09-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_arrivaltime_flights_arrival_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flights',
        ),
    ]
