# Generated by Django 5.0.7 on 2024-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_list_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(max_length=99, null=True),
        ),
    ]
