# Generated by Django 5.0.7 on 2024-10-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room_list',
        ),
    ]
