# Generated by Django 5.0.7 on 2024-10-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_delete_room_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='deluxe',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='executive',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='honeymoon',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='single',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
