# Generated by Django 5.0.7 on 2024-10-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_list_deluxe_list_executive_list_honeymoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='four',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='one',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='three',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='two',
            field=models.TextField(max_length=99, null=True),
        ),
    ]
