# Generated by Django 5.0.7 on 2024-10-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_list_fifth_list_first_list_fourth_list_second_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='fifth',
            new_name='fifth_img',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='first',
            new_name='first_img',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='deluxe',
            new_name='first_room',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='four',
            new_name='first_room_type',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='fourth',
            new_name='fourth_img',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='second',
            new_name='second_img',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='executive',
            new_name='second_room',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='one',
            new_name='second_room_type',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='sixth',
            new_name='sixth_img',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='third',
            new_name='third_img',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='honeymoon',
            new_name='third_room',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='three',
            new_name='third_room_type',
        ),
        migrations.RemoveField(
            model_name='list',
            name='single',
        ),
        migrations.RemoveField(
            model_name='list',
            name='two',
        ),
    ]
