# Generated by Django 5.0.7 on 2024-10-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_rename_fifth_list_fifth_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='first_room',
            new_name='first_room_img',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='second_room',
            new_name='second_room_img',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='third_room',
            new_name='third_room_img',
        ),
    ]
