# Generated by Django 5.0.7 on 2024-10-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_rename_first_room_list_first_room_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='desc',
            field=models.TextField(max_length=9999, null=True),
        ),
    ]
