# Generated by Django 5.0.7 on 2024-10-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_list_price_list_first_room_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='desc',
            new_name='first_desc',
        ),
        migrations.AddField(
            model_name='list',
            name='second_desc',
            field=models.TextField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='third_desc',
            field=models.TextField(max_length=9999, null=True),
        ),
    ]
