# Generated by Django 5.0.7 on 2024-10-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_rename_desc_list_first_desc_list_second_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='desc',
            field=models.TextField(max_length=999, null=True),
        ),
    ]
