# Generated by Django 5.0.7 on 2024-10-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_list_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='desc',
            new_name='hotel_desc',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='img',
            new_name='hotel_img',
        ),
    ]
