# Generated by Django 5.0.7 on 2024-10-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(max_length=99, null=True),
        ),
    ]
