# Generated by Django 5.0.7 on 2024-10-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0002_cars_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
