# Generated by Django 5.0.7 on 2024-10-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0003_alter_cars_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='slug',
        ),
    ]
